### PR TITLE
add test for complicated tag and fix issue for it

### PR DESCRIPTION
**Pull request by Vergenter**
Connected with issue https://github.com/lenforiee/OsuPyParser/issues/1

I formatted unittests to work with default python unittests. I added file with beatmap with tag that caused bug and added unittest for it.

In second commit I successfully solved issue by replacing usage of "in" keyword with line.startswith(key).
It passes unit test for it and it worked for me for 1000+ files.

### CODE REVIEW

**Comment by RealistikDash** [comment]
Hey! I do like your changes myself but dropping my two cents in, I personally think it would be better not to bundle the `.osu` test map with the repo (its not made by its creator etc) but rather download it along with the tests.

**Comment by Vergenter** [comment]
This is a good and bad idea at the same time:
pros:
Working with real data.
Solves problem with license.
cons:
Dependency on other service -> accessing other services and downloading = more code that need to be maintained.
Added complexity for testing -> testing should be as straightforward as possible.
It could be hard to find example for every unit test -> It's easier to manually edit beatmap file.

An easy solution is to create the own beatmap file(that will be distributed using project license), that will mimic some existing beatmap and modify it to include the required features. The drawback of this is that it loses strict connection to reality.

I'm now looking for some official information about osu beatmap file licensing. From terms of service, user that uploads a file to osu! server, gives osu! rights to it.(source: https://osu.ppy.sh/legal/en/Terms#user-submissions-and-content-removal)  Later, osu! is distributing it, but I couldn't find under what license. In beatmap file there is information who is author of it, probably that is enough to use it in this project.

**Comment by Vergenter** [comment]
I found and fixed regression connected with change to `startswith(key)`. Opening some beatmaps had been failing because they were encoded using UTF8 with BOM, now they are handled correctly.

**Comment by lenforiee** [comment]
Hey sorry that responding to it took me 2 months but I am planning to rewrite it very soon as the code quality is far worse than what I currently write.
Anyways thanks for contribution!

**Pull request merged**
